theme: jekyll-theme-cayman
title: La tuberculosis y el por qué de su tasa de mortalidad: Una comparativa entre países y sus factores de riesgo
description: Grupo 2124 de Seminario de Proyecto de Grado 2022-1
